FROM node:20.14.0

ENV APP_PATH=/app/client \
    NODE_ENV=development \
    XDG_CACHE_HOME="/usr/local/pnpm"

# Install pnpm globally
RUN npm install -g pnpm@9.9.0

# copy entrypoint scripts and grant execution permissions
COPY ./docker/dev-docker-entrypoint.sh /usr/local/bin/dev-entrypoint.sh
RUN chmod +x /usr/local/bin/dev-entrypoint.sh

# navigate to app directory
WORKDIR $APP_PATH

EXPOSE 3001

