name: Nightly Docker

# Scope cache for each build independently https://docs.docker.com/build/cache/backends/gha/#scope

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          cache-from: |
            type=gha,scope=docker
          cache-to: |
            type=gha,mode=max,scope=docker
          tags: docker:latest
          push: false

  development_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          cache-from: |
            type=gha,scope=development_docker
          cache-to: |
            type=gha,mode=max,scope=development_docker
          file: Dockerfile.development
          tags: development:latest
          push: false
